# this is for the graphs in the introduction
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(dplyr)


# Load country data at medium resolution
australia <- ne_countries(scale = "medium", country = "Australia", returnclass = "sf")

# Sample data
data <- read.csv("C:/Users/tsto3616/thesis/hookworm prev Aus.csv")

All<- ggplot(data = australia) +
  geom_sf(fill = "white", color = "black") +
  geom_point(data = data, aes(x = Longitude, y = Latitude, color = Prevalence, size = Samples), alpha = 0.5) + scale_color_gradientn(colors = c("yellow", "red"), limits= c(0, 100)) + ggtitle("Australia with Data Points") +
  scale_size_continuous(limits = c(0, 800), range = c(2, 6)) + coord_sf(ylim = c(-5, -45), xlim = c(110, 155)) + theme_minimal()

All

Uste<- data %>% filter(Species == "Uncinaria stenocephala")

Uste <- ggplot(data = australia) +
  geom_sf(fill = "white", color = "black") +
  geom_point(data = Uste, aes(x = Longitude, y = Latitude, color = Prevalence, size = Samples), alpha = 0.5)  +scale_color_gradientn(colors = c("yellow", "red"), limits = c(0, 100)) + ggtitle("Australia with Data Points") +
  scale_size_continuous(limits = c(0, 800), range = c(2, 6)) + coord_sf(ylim = c(-5, -45), xlim = c(110, 155)) + theme_minimal()
  
Uste
  
Acey<- data %>% filter(Species == "Ancylostoma ceylanicum")

Acey <- ggplot(data = australia) +
  geom_sf(fill = "white", color = "black") +
  geom_point(data = Acey, aes(x = Longitude, y = Latitude, color = Prevalence, size = Samples), alpha = 0.5)  +scale_color_gradientn(colors = c("yellow", "red"), limits = c(0, 100)) + ggtitle("Australia with Data Points") +
  scale_size_continuous(limits = c(0, 800), range = c(2, 6)) + coord_sf(ylim = c(-5, -45), xlim = c(110, 155)) + theme_minimal()

Acey  

Acan<- data %>% filter(Species == "Ancylostoma caninum")

Acan <- ggplot(data = australia) +
  geom_sf(fill = "white", color = "black") +
  geom_point(data = Acan, aes(x = Longitude, y = Latitude, color = Prevalence, size = Samples), alpha = 0.5)  +scale_color_gradientn(colors = c("yellow", "red"), limits = c(0, 100)) + ggtitle("Australia with Data Points") +
  scale_size_continuous(limits = c(0, 800), range = c(2, 6)) + coord_sf(ylim = c(-5, -45), xlim = c(110, 155)) + theme_minimal()

Acan

Atub<- data %>% filter(Species == "Ancylostoma tubaeforme")

Atub <- ggplot(data = australia) +
  geom_sf(fill = "white", color = "black") +
  geom_point(data = Atub, aes(x = Longitude, y = Latitude, color = Prevalence, size = Samples), alpha = 0.5)  +scale_color_gradientn(colors = c("yellow", "red"), limits = c(0, 100)) + ggtitle("Australia with Data Points") +
  scale_size_continuous(limits = c(0, 800), range = c(2, 6)) + coord_sf(ylim = c(-5, -45), xlim = c(110, 155)) + theme_minimal()

Atub


